# standby: 0
# grab_bullets: 100
# request_control: 10
# takeoff: 250
# fly_to_car: 250
# serve_car: 100
# drop_bullets: 100
# back_to_normal_altitude: 200
# fly_back: 200
# visual_servo_landing: 200
# landing: 200
# release_control: 10

duration: [0, 100, 10, 250, 250, 100, 100, 200, 200, 200, 200, 10]
