pid: {
 xy: {kp: 1.0, ki: 0, kd: 0.1, db: 0.1, it: 0, Emax: 2, Pmax: 6, Imax: 0, Dmax: 0, Omax: 6},
 z: {kp: 1.0, ki: 0, kd: 0.1, db: 0.1, it: 0, Emax: 2, Pmax: 6, Imax: 0, Dmax: 0, Omax: 6},
 yaw: {kp: 2.0, ki: 0, kd: 0, db: 0.1, it: 0, Emax: 2, Pmax: 6, Imax: 0, Dmax: 0, Omax: 6}
}

